/**
 * Pollution tracking and management system.
 * <p>
 * This package manages environmental pollution caused by industrial machines,
 * tracking both temporary (chunk-based) and permanent (global) pollution levels.
 * <p>
 * <b>Key Components:</b>
 * <ul>
 *   <li>{@link cn.minerealms.iic.pollution.PollutionManager} - Central pollution tracking and calculation</li>
 *   <li>{@link cn.minerealms.iic.pollution.visual.PollutionVisualEffects} - Visual effects for high pollution</li>
 * </ul>
 * <p>
 * <b>Pollution System:</b>
 * <ul>
 *   <li><b>Temporary Pollution:</b> Chunk-based pollution that spreads and decays over time</li>
 *   <li><b>Permanent Pollution:</b> Global accumulation that never decays, representing long-term environmental damage</li>
 *   <li><b>Visual Effects:</b> Screen effects (blur, darkness) triggered at high pollution levels</li>
 * </ul>
 * <p>
 * Pollution is generated by GregTech machines based on their voltage tier and activity.
 * Higher tier machines produce more pollution, contributing to both local and global pollution pools.
 *
 * @since 1.0.0
 * @author ImprovedMobs Team
 */
package cn.minerealms.iic.pollution;
