pluginManagement {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://maven.aliyun.com/repository/public' }
        maven {
            name = "Flemmli97"
            url "https://maven.blazing-coop.net/releases"
        }

        gradlePluginPortal()
    }
}

rootProject.name = "IntegratedIndustrialCraft"
